---
- name: turns a cloudinit.img into a proxmox template. 
  hosts: proxmoxnodes
  roles:
    - homeserver.vms.maketemplate

- name: Download and install the template used by cloud init template. 
  hosts: proxmoxnodes
  roles:
    - homeserver.vms.makevm