---
- name: Turns a cloudinit.img into a proxmox template. 
  hosts: proxmoxnodes
  roles:
    - homeserver.vms.maketemplate

- name: Creates a VM out of a existing proxmox template with spesific hardware configruation.
  hosts: proxmoxnodes
  roles:
    - homeserver.vms.makevm